springdoc:
  swagger-ui:
    use-root-path: true

spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/parking}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER:admin}
    password: ${PGPASSWORD:123}
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always